import { JSONLanguageFormat } from "../@types";

const iso693Regex =
  /^(?:(aa|ab|ae|af|ak|am|an|ar|as|av|ay|az|ba|be|bg|bi|bm|bn|bo|br|bs|ca|ce|ch|co|cr|cs|cu|cv|cy|da|de|dv|dz|ee|el|en|eo|es|et|eu|fa|ff|fi|fj|fo|fr|fy|ga|gd|gl|gn|gu|gv|ha|he|hi|ho|hr|ht|hu|hy|hz|ia|id|ie|ig|ii|ik|io|is|it|iu|ja|jv|ka|kg|ki|kj|kk|kl|km|kn|ko|kr|ks|ku|kv|kw|ky|la|lb|lg|li|ln|lo|lt|lu|lv|mg|mh|mi|mk|ml|mn|mr|ms|mt|my|na|nb|nd|ne|ng|nl|nn|no|nr|nv|ny|oc|oj|om|or|os|pa|pi|pl|ps|pt|qu|rm|rn|ro|ru|rw|sa|sc|sd|se|sg|si|sk|sl|sm|sn|so|sq|sr|ss|st|su|sv|sw|ta|te|tg|th|ti|tk|tl|tn|to|tr|ts|tt|tw|ty|ug|uk|ur|uz|ve|vi|vo|wa|wo|xh|yi|yo|za|zh|zu))$/;
const iso6932Regex =
  /^(?:(aar|abk|ave|afr|aka|amh|arg|ara|asm|ava|aym|aze|bak|bel|bul|bis|bam|ben|bod|bre|bos|cat|che|cha|cos|cre|ces|chu|chv|cym|dan|deu|div|dzo|ewe|ell|eng|epo|spa|est|eus|fas|ful|fin|fij|fao|fra|fry|gle|gla|glg|grn|guj|glv|hau|heb|hin|hmo|hrv|hat|hun|hye|her|ina|ind|ile|ibo|iii|ipk|ido|isl|ita|iku|jpn|jav|kat|kon|kik|kua|kaz|kal|khm|kan|kor|kau|kas|kur|kom|cor|kir|lat|ltz|lug|lim|lin|lao|lit|lub|lav|mlg|mah|mri|mkd|mal|mon|mar|msa|mlt|mya|nau|nob|nde|nep|ndo|nld|nno|nor|nbl|nav|nya|oci|oji|orm|ori|oss|pan|pli|pol|pus|por|que|roh|run|ron|rus|kin|san|srd|snd|sme|sag|sin|slk|slv|smo|sna|som|sqi|srp|ssw|sot|sun|swe|swa|tam|tel|tgk|tha|tir|tuk|tgl|tsn|ton|tur|tso|tat|twi|tah|uig|ukr|urd|uzb|ven|vie|vol|wln|wol|xho|yid|yor|zha|zho|zul))$/;

const iso693EnglishNames = [
  "Catalan, Valencian",
  "Chichewa, Chewa, Nyanja",
  "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic",
  "Divehi, Dhivehi, Maldivian",
  "Dutch, Flemish",
  "Gaelic, Scottish Gaelic",
  "Greek, Modern (1453–)",
  "Haitian, Haitian Creole",
  "Interlingue, Occidental",
  "Kalaallisut, Greenlandic",
  "Kikuyu, Gikuyu",
  "Kirghiz, Kyrgyz",
  "Kuanyama, Kwanyama",
  "Limburgan, Limburger, Limburgish",
  "Luxembourgish, Letzeburgesch",
  "Navajo, Navaho",
  "Ossetian, Ossetic",
  "Pashto, Pushto",
  "Punjabi, Panjabi",
  "Romanian, Moldavian, Moldovan",
  "Sichuan Yi, Nuosu",
  "Sinhala, Sinhalese",
  "Spanish, Castilian",
  "Uighur, Uyghur",
  "Zhuang, Chuang",
  "Abkhazian",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Assamese",
  "Avaric",
  "Avestan",
  "Aymara",
  "Azerbaijani",
  "Bambara",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bislama",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Central Khmer",
  "Chamorro",
  "Chechen",
  "Chinese",
  "Chuvash",
  "Cornish",
  "Corsican",
  "Cree",
  "Croatian",
  "Czech",
  "Danish",
  "Dzongkha",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Faroese",
  "Fijian",
  "Finnish",
  "French",
  "Fulah",
  "Galician",
  "Ganda",
  "Georgian",
  "German",
  "Guarani",
  "Gujarati",
  "Hausa",
  "Hebrew",
  "Herero",
  "Hindi",
  "Hiri Motu",
  "Hungarian",
  "Icelandic",
  "Ido",
  "Igbo",
  "Indonesian",
  "Interlingua (International Auxiliary Language Association)",
  "Inuktitut",
  "Inupiaq",
  "Irish",
  "ISO language name",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kanuri",
  "Kashmiri",
  "Kazakh",
  "Kinyarwanda",
  "Komi",
  "Kongo",
  "Korean",
  "Kurdish",
  "Lao",
  "Latin",
  "Latvian",
  "Lingala",
  "Lithuanian",
  "Luba-Katanga",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Manx",
  "Maori",
  "Marathi",
  "Marshallese",
  "Mongolian",
  "Nauru",
  "Ndonga",
  "Nepali",
  "North Ndebele",
  "Northern Sami",
  "Norwegian",
  "Norwegian Bokmål",
  "Norwegian Nynorsk",
  "Occitan",
  "Ojibwa",
  "Oriya",
  "Oromo",
  "Pali",
  "Persian",
  "Polish",
  "Portuguese",
  "Quechua",
  "Romansh",
  "Rundi",
  "Russian",
  "Samoan",
  "Sango",
  "Sanskrit",
  "Sardinian",
  "Serbian",
  "Shona",
  "Sindhi",
  "Slovak",
  "Slovenian",
  "Somali",
  "South Ndebele",
  "Southern Sotho",
  "Sundanese",
  "Swahili",
  "Swati",
  "Swedish",
  "Tagalog",
  "Tahitian",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Tonga (Tonga Islands)",
  "Tsonga",
  "Tswana",
  "Turkish",
  "Turkmen",
  "Twi",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Venda",
  "Vietnamese",
  "Volapük",
  "Walloon",
  "Welsh",
  "Western Frisian",
  "Wolof",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zulu",
];

const iso693NativeNames = [
  "(originally:) Occidental, (after WWII:) Interlingue",
  "azərbaycan dili, تۆرکجه",
  "Bahasa Melayu, بهاس ملايو‎",
  "català, valencià",
  "čeština, český jazyk",
  "chiCheŵa, chinyanja",
  "corsu, lingua corsa",
  "eesti, eesti keel",
  "euskara, euskera",
  "Fulfulde, Pulaar, Pular",
  "Gaelg, Gailck",
  "Iñupiaq, Iñupiatun",
  "język polski, polszczyzna",
  "kalaallisut, kalaallit oqaasii",
  "Kurdî, کوردی‎",
  "latine, lingua latina",
  "Nederlands, Vlaams",
  "occitan, lenga d'òc",
  "Oʻzbek, Ўзбек, أۇزبېك‎",
  "Română, Moldovenească",
  "Runa Simi, Kichwa",
  "Saɯ cueŋƅ, Saw cuengh",
  "slovenčina, slovenský jazyk",
  "Slovenski jezik, Slovenščina",
  "Soomaaliga, af Soomaali",
  "suomi, suomen kieli",
  "Türkmençe, Türkmen dili",
  "авар мацӀ, магӀарул мацӀ",
  "аҧсуа бызшәа, аҧсшәа",
  "Кыргызча, Кыргыз тили",
  "татар теле, tatar tele",
  "тоҷикӣ, toçikī, تاجیکی‎",
  "ئۇيغۇرچە‎, Uyghurche",
  "कॉशुर, کٲشُر‎",
  "पालि, पाळि",
  "संस्कृतम्, 𑌸𑌂𑌸𑍍𑌕𑍃𑌤𑌮𑍍",
  "सिंधी, سنڌي‎",
  "हिन्दी, हिंदी",
  "ਪੰਜਾਬੀ, پنجابی‎",
  "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ",
  "ꦧꦱꦗꦮ, Basa Jawa",
  "中文 (Zhōngwén), 汉语, 漢語",
  "(Hausa) هَوُسَ",
  "Afaan Oromoo",
  "Afaraf",
  "Afrikaans",
  "Akan",
  "aragonés",
  "Asụsụ Igbo",
  "Avañe'ẽ",
  "avesta",
  "aymar aru",
  "Bahasa Indonesia",
  "bamanankan",
  "Basa Sunda",
  "Bislama",
  "bosanski jezik",
  "brezhoneg",
  "Chamoru",
  "chiShona",
  "Cymraeg",
  "dansk",
  "Davvisámegiella",
  "Deutsch",
  "Diné bizaad",
  "Dorerin Naoero",
  "English",
  "Español",
  "Esperanto",
  "Eʋegbe",
  "Faka Tonga",
  "fiteny malagasy",
  "føroyskt",
  "français",
  "Frysk",
  "Gaeilge",
  "gagana fa'a Samoa",
  "Gàidhlig",
  "Galego",
  "Gĩkũyũ",
  "Hiri Motu",
  "hrvatski jezik",
  "Ido",
  "Ikinyarwanda",
  "Ikirundi",
  "Interlingua",
  "isiNdebele",
  "isiNdebele",
  "isiXhosa",
  "isiZulu",
  "Íslenska",
  "Italiano",
  "Kajin M̧ajeļ",
  "Kanuri",
  "Kernewek",
  "Kikongo",
  "Kiluba",
  "Kiswahili",
  "Kreyòl ayisyen",
  "Kuanyama",
  "latviešu valoda",
  "Lëtzebuergesch",
  "lietuvių kalba",
  "Limburgs",
  "Lingála",
  "Luganda",
  "magyar",
  "Malti",
  "Norsk",
  "Norsk Bokmål",
  "Norsk Nynorsk",
  "Otjiherero",
  "Owambo",
  "Português",
  "Reo Tahiti",
  "Rumantsch Grischun",
  "sardu",
  "Sesotho",
  "Setswana",
  "Shqip",
  "SiSwati",
  "Svenska",
  "te reo Māori",
  "Tiếng Việt",
  "Tshivenḓa",
  "Türkçe",
  "Twi",
  "Volapük",
  "vosa Vakaviti",
  "Walon",
  "Wikang Tagalog",
  "Wollof",
  "Xitsonga",
  "yângâ tî sängö",
  "Yorùbá",
  "Ελληνικά",
  "башҡорт теле",
  "беларуская мова",
  "български език",
  "ирон ӕвзаг",
  "коми кыв",
  "қазақ тілі",
  "македонски јазик",
  "Монгол хэл",
  "нохчийн мотт",
  "русский",
  "српски језик",
  "Українська",
  "чӑваш чӗлхи",
  "ѩзыкъ словѣньскъ",
  "ქართული",
  "Հայերեն",
  "ትግርኛ",
  "አማርኛ",
  "नेपाली",
  "मराठी",
  "অসমীয়া",
  "বাংলা",
  "ગુજરાતી",
  "ଓଡ଼ିଆ",
  "தமிழ்",
  "తెలుగు",
  "ಕನ್ನಡ",
  "മലയാളം",
  "සිංහල",
  "ไทย",
  "ພາສາລາວ",
  "བོད་ཡིག",
  "རྫོང་ཁ",
  "ဗမာစာ",
  "ᐃᓄᒃᑎᑐᑦ",
  "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  "ᓀᐦᐃᔭᐍᐏᐣ",
  "한국어",
  "ꆈꌠ꒿ Nuosuhxop",
  "日本語 (にほんご)",
];

export function inferLanguage(value: string): JSONLanguageFormat | undefined {
  if (iso693Regex.test(value)) {
    return {
      name: "language",
      variant: "iso693-1",
    };
  }

  if (iso6932Regex.test(value)) {
    return {
      name: "language",
      variant: "iso693-2",
    };
  }

  if (iso693EnglishNames.includes(value)) {
    return {
      name: "language",
      variant: "english",
    };
  }

  if (iso693NativeNames.includes(value)) {
    return {
      name: "language",
      variant: "native",
    };
  }

  return undefined;
}
